import type {
  Intersection,
  Incident,
  TrafficStats,
  HourlyData,
  ZoneStats,
} from "./types";

export const intersections: Intersection[] = [
  {
    id: "int-001",
    name: "Main St & 1st Ave",
    location: "Downtown Core",
    lat: 40.7128,
    lng: -74.006,
    density: "heavy",
    vehicleCount: 342,
    avgSpeed: 18,
    status: "warning",
    cameraActive: true,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-001-n",
        intersectionId: "int-001",
        direction: "north",
        state: "green",
        mode: "auto",
        greenDuration: 45,
        yellowDuration: 5,
        redDuration: 50,
        cyclePosition: 30,
        lastChanged: new Date(Date.now() - 30000).toISOString(),
      },
      {
        id: "sig-001-s",
        intersectionId: "int-001",
        direction: "south",
        state: "green",
        mode: "auto",
        greenDuration: 45,
        yellowDuration: 5,
        redDuration: 50,
        cyclePosition: 30,
        lastChanged: new Date(Date.now() - 30000).toISOString(),
      },
      {
        id: "sig-001-e",
        intersectionId: "int-001",
        direction: "east",
        state: "red",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 75,
        lastChanged: new Date(Date.now() - 45000).toISOString(),
      },
      {
        id: "sig-001-w",
        intersectionId: "int-001",
        direction: "west",
        state: "red",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 75,
        lastChanged: new Date(Date.now() - 45000).toISOString(),
      },
    ],
  },
  {
    id: "int-002",
    name: "Broadway & 5th St",
    location: "Midtown",
    lat: 40.7549,
    lng: -73.984,
    density: "moderate",
    vehicleCount: 198,
    avgSpeed: 28,
    status: "normal",
    cameraActive: true,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-002-n",
        intersectionId: "int-002",
        direction: "north",
        state: "red",
        mode: "auto",
        greenDuration: 35,
        yellowDuration: 5,
        redDuration: 60,
        cyclePosition: 60,
        lastChanged: new Date(Date.now() - 20000).toISOString(),
      },
      {
        id: "sig-002-s",
        intersectionId: "int-002",
        direction: "south",
        state: "red",
        mode: "auto",
        greenDuration: 35,
        yellowDuration: 5,
        redDuration: 60,
        cyclePosition: 60,
        lastChanged: new Date(Date.now() - 20000).toISOString(),
      },
      {
        id: "sig-002-e",
        intersectionId: "int-002",
        direction: "east",
        state: "green",
        mode: "auto",
        greenDuration: 35,
        yellowDuration: 5,
        redDuration: 60,
        cyclePosition: 20,
        lastChanged: new Date(Date.now() - 10000).toISOString(),
      },
      {
        id: "sig-002-w",
        intersectionId: "int-002",
        direction: "west",
        state: "green",
        mode: "auto",
        greenDuration: 35,
        yellowDuration: 5,
        redDuration: 60,
        cyclePosition: 20,
        lastChanged: new Date(Date.now() - 10000).toISOString(),
      },
    ],
  },
  {
    id: "int-003",
    name: "Harbor Blvd & Ocean Dr",
    location: "Waterfront",
    lat: 40.6892,
    lng: -74.0445,
    density: "low",
    vehicleCount: 87,
    avgSpeed: 42,
    status: "normal",
    cameraActive: true,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-003-n",
        intersectionId: "int-003",
        direction: "north",
        state: "green",
        mode: "auto",
        greenDuration: 30,
        yellowDuration: 5,
        redDuration: 65,
        cyclePosition: 15,
        lastChanged: new Date(Date.now() - 15000).toISOString(),
      },
      {
        id: "sig-003-s",
        intersectionId: "int-003",
        direction: "south",
        state: "green",
        mode: "auto",
        greenDuration: 30,
        yellowDuration: 5,
        redDuration: 65,
        cyclePosition: 15,
        lastChanged: new Date(Date.now() - 15000).toISOString(),
      },
      {
        id: "sig-003-e",
        intersectionId: "int-003",
        direction: "east",
        state: "red",
        mode: "auto",
        greenDuration: 30,
        yellowDuration: 5,
        redDuration: 65,
        cyclePosition: 50,
        lastChanged: new Date(Date.now() - 35000).toISOString(),
      },
      {
        id: "sig-003-w",
        intersectionId: "int-003",
        direction: "west",
        state: "red",
        mode: "auto",
        greenDuration: 30,
        yellowDuration: 5,
        redDuration: 65,
        cyclePosition: 50,
        lastChanged: new Date(Date.now() - 35000).toISOString(),
      },
    ],
  },
  {
    id: "int-004",
    name: "Industrial Pkwy & Route 9",
    location: "Industrial Zone",
    lat: 40.7282,
    lng: -74.0776,
    density: "gridlock",
    vehicleCount: 521,
    avgSpeed: 5,
    status: "critical",
    cameraActive: true,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-004-n",
        intersectionId: "int-004",
        direction: "north",
        state: "red",
        mode: "manual",
        greenDuration: 60,
        yellowDuration: 5,
        redDuration: 35,
        cyclePosition: 80,
        lastChanged: new Date(Date.now() - 60000).toISOString(),
      },
      {
        id: "sig-004-s",
        intersectionId: "int-004",
        direction: "south",
        state: "red",
        mode: "manual",
        greenDuration: 60,
        yellowDuration: 5,
        redDuration: 35,
        cyclePosition: 80,
        lastChanged: new Date(Date.now() - 60000).toISOString(),
      },
      {
        id: "sig-004-e",
        intersectionId: "int-004",
        direction: "east",
        state: "yellow",
        mode: "manual",
        greenDuration: 60,
        yellowDuration: 5,
        redDuration: 35,
        cyclePosition: 95,
        lastChanged: new Date(Date.now() - 5000).toISOString(),
      },
      {
        id: "sig-004-w",
        intersectionId: "int-004",
        direction: "west",
        state: "yellow",
        mode: "manual",
        greenDuration: 60,
        yellowDuration: 5,
        redDuration: 35,
        cyclePosition: 95,
        lastChanged: new Date(Date.now() - 5000).toISOString(),
      },
    ],
  },
  {
    id: "int-005",
    name: "University Ave & College Rd",
    location: "University District",
    lat: 40.7282,
    lng: -73.9942,
    density: "moderate",
    vehicleCount: 215,
    avgSpeed: 24,
    status: "normal",
    cameraActive: false,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-005-n",
        intersectionId: "int-005",
        direction: "north",
        state: "green",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 25,
        lastChanged: new Date(Date.now() - 25000).toISOString(),
      },
      {
        id: "sig-005-s",
        intersectionId: "int-005",
        direction: "south",
        state: "green",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 25,
        lastChanged: new Date(Date.now() - 25000).toISOString(),
      },
      {
        id: "sig-005-e",
        intersectionId: "int-005",
        direction: "east",
        state: "red",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 65,
        lastChanged: new Date(Date.now() - 40000).toISOString(),
      },
      {
        id: "sig-005-w",
        intersectionId: "int-005",
        direction: "west",
        state: "red",
        mode: "auto",
        greenDuration: 40,
        yellowDuration: 5,
        redDuration: 55,
        cyclePosition: 65,
        lastChanged: new Date(Date.now() - 40000).toISOString(),
      },
    ],
  },
  {
    id: "int-006",
    name: "Airport Connector & Terminal Rd",
    location: "Airport Zone",
    lat: 40.6413,
    lng: -73.7781,
    density: "heavy",
    vehicleCount: 389,
    avgSpeed: 15,
    status: "warning",
    cameraActive: true,
    lastUpdated: new Date().toISOString(),
    signals: [
      {
        id: "sig-006-n",
        intersectionId: "int-006",
        direction: "north",
        state: "red",
        mode: "auto",
        greenDuration: 50,
        yellowDuration: 5,
        redDuration: 45,
        cyclePosition: 70,
        lastChanged: new Date(Date.now() - 50000).toISOString(),
      },
      {
        id: "sig-006-s",
        intersectionId: "int-006",
        direction: "south",
        state: "red",
        mode: "auto",
        greenDuration: 50,
        yellowDuration: 5,
        redDuration: 45,
        cyclePosition: 70,
        lastChanged: new Date(Date.now() - 50000).toISOString(),
      },
      {
        id: "sig-006-e",
        intersectionId: "int-006",
        direction: "east",
        state: "green",
        mode: "auto",
        greenDuration: 50,
        yellowDuration: 5,
        redDuration: 45,
        cyclePosition: 40,
        lastChanged: new Date(Date.now() - 30000).toISOString(),
      },
      {
        id: "sig-006-w",
        intersectionId: "int-006",
        direction: "west",
        state: "green",
        mode: "auto",
        greenDuration: 50,
        yellowDuration: 5,
        redDuration: 45,
        cyclePosition: 40,
        lastChanged: new Date(Date.now() - 30000).toISOString(),
      },
    ],
  },
];

export const incidents: Incident[] = [
  {
    id: "inc-001",
    type: "accident",
    title: "Multi-vehicle collision",
    description:
      "3-car accident blocking 2 lanes. Emergency services on scene.",
    intersectionId: "int-001",
    location: "Main St & 1st Ave",
    severity: "high",
    status: "responding",
    reportedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    resolvedAt: null,
    affectedLanes: 2,
    estimatedClearance: new Date(Date.now() + 35 * 60000).toISOString(),
  },
  {
    id: "inc-002",
    type: "congestion",
    title: "Severe gridlock",
    description:
      "Traffic backed up over 2km due to construction diversion. Manual signal control activated.",
    intersectionId: "int-004",
    location: "Industrial Pkwy & Route 9",
    severity: "critical",
    status: "active",
    reportedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    resolvedAt: null,
    affectedLanes: 4,
    estimatedClearance: new Date(Date.now() + 120 * 60000).toISOString(),
  },
  {
    id: "inc-003",
    type: "signal_fault",
    title: "Signal controller malfunction",
    description:
      "Traffic signal controller unit failure. Signals operating in flashing mode.",
    intersectionId: "int-005",
    location: "University Ave & College Rd",
    severity: "medium",
    status: "responding",
    reportedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    resolvedAt: null,
    affectedLanes: 0,
    estimatedClearance: new Date(Date.now() + 60 * 60000).toISOString(),
  },
  {
    id: "inc-004",
    type: "roadwork",
    title: "Emergency water main repair",
    description:
      "Burst water main requiring immediate road closure. One lane open with traffic control.",
    intersectionId: null,
    location: "Harbor Blvd, between Oak St and Pine St",
    severity: "medium",
    status: "active",
    reportedAt: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    resolvedAt: null,
    affectedLanes: 2,
    estimatedClearance: new Date(Date.now() + 4 * 60 * 60000).toISOString(),
  },
  {
    id: "inc-005",
    type: "breakdown",
    title: "Heavy vehicle breakdown",
    description:
      "Articulated truck broken down in right lane. Tow truck dispatched.",
    intersectionId: "int-006",
    location: "Airport Connector & Terminal Rd",
    severity: "low",
    status: "responding",
    reportedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    resolvedAt: null,
    affectedLanes: 1,
    estimatedClearance: new Date(Date.now() + 20 * 60000).toISOString(),
  },
  {
    id: "inc-006",
    type: "accident",
    title: "Minor fender bender",
    description: "Two vehicles involved. No injuries. Vehicles moved to shoulder.",
    intersectionId: "int-002",
    location: "Broadway & 5th St",
    severity: "low",
    status: "resolved",
    reportedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    affectedLanes: 0,
    estimatedClearance: null,
  },
];

export const currentStats: TrafficStats = {
  totalVehicles: 1752,
  avgSpeed: 22,
  activeIncidents: 5,
  signalFaults: 1,
  congestionLevel: 68,
  throughput: 4280,
  timestamp: new Date().toISOString(),
};

export const hourlyData: HourlyData[] = [
  { hour: "00:00", vehicles: 320, avgSpeed: 52, incidents: 0 },
  { hour: "01:00", vehicles: 180, avgSpeed: 58, incidents: 0 },
  { hour: "02:00", vehicles: 120, avgSpeed: 61, incidents: 0 },
  { hour: "03:00", vehicles: 95, avgSpeed: 63, incidents: 0 },
  { hour: "04:00", vehicles: 140, avgSpeed: 60, incidents: 1 },
  { hour: "05:00", vehicles: 380, avgSpeed: 48, incidents: 0 },
  { hour: "06:00", vehicles: 820, avgSpeed: 35, incidents: 1 },
  { hour: "07:00", vehicles: 1450, avgSpeed: 22, incidents: 2 },
  { hour: "08:00", vehicles: 1820, avgSpeed: 18, incidents: 3 },
  { hour: "09:00", vehicles: 1650, avgSpeed: 24, incidents: 2 },
  { hour: "10:00", vehicles: 1380, avgSpeed: 28, incidents: 1 },
  { hour: "11:00", vehicles: 1290, avgSpeed: 30, incidents: 1 },
  { hour: "12:00", vehicles: 1520, avgSpeed: 26, incidents: 2 },
  { hour: "13:00", vehicles: 1480, avgSpeed: 27, incidents: 1 },
  { hour: "14:00", vehicles: 1350, avgSpeed: 29, incidents: 1 },
  { hour: "15:00", vehicles: 1580, avgSpeed: 25, incidents: 2 },
  { hour: "16:00", vehicles: 1920, avgSpeed: 19, incidents: 3 },
  { hour: "17:00", vehicles: 2150, avgSpeed: 15, incidents: 4 },
  { hour: "18:00", vehicles: 1980, avgSpeed: 17, incidents: 3 },
  { hour: "19:00", vehicles: 1620, avgSpeed: 23, incidents: 2 },
  { hour: "20:00", vehicles: 1280, avgSpeed: 31, incidents: 1 },
  { hour: "21:00", vehicles: 980, avgSpeed: 38, incidents: 1 },
  { hour: "22:00", vehicles: 720, avgSpeed: 44, incidents: 0 },
  { hour: "23:00", vehicles: 480, avgSpeed: 49, incidents: 0 },
];

export const zoneStats: ZoneStats[] = [
  {
    zone: "Downtown Core",
    intersections: 12,
    activeIncidents: 2,
    avgCongestion: 72,
    status: "warning",
  },
  {
    zone: "Midtown",
    intersections: 18,
    activeIncidents: 1,
    avgCongestion: 45,
    status: "normal",
  },
  {
    zone: "Waterfront",
    intersections: 8,
    activeIncidents: 0,
    avgCongestion: 28,
    status: "normal",
  },
  {
    zone: "Industrial Zone",
    intersections: 6,
    activeIncidents: 1,
    avgCongestion: 91,
    status: "critical",
  },
  {
    zone: "University District",
    intersections: 10,
    activeIncidents: 1,
    avgCongestion: 55,
    status: "warning",
  },
  {
    zone: "Airport Zone",
    intersections: 5,
    activeIncidents: 1,
    avgCongestion: 63,
    status: "warning",
  },
];
